### ISSUE TITLE
当使用iyuu辅种，下载器里有两个同名的种子任务，此时Emby同步删除种子的时候，并不能工作。

### ISSUE THREAD

**Issue by CookieJaySJ** [thsrite/emby_sync_del_nt#10]
首先测试了下载列表里只有一个种子，无辅种，同步删除插件可以工作：
<img width="1603" alt="截屏2023-04-08 12 56 49" src="https://user-images.githubusercontent.com/10297471/230704034-3c2707cd-9d46-4388-af25-396c39db1c99.png">

当下载列表里有同样名字的辅种，同步删除插件并不能删掉种子任务：
<img width="1603" alt="截屏2023-04-08 12 55 59" src="https://user-images.githubusercontent.com/10297471/230704069-f77036c9-54cc-4847-9021-ba7da9f34715.png">

**Comment by thsrite** [comment]
这块去nt提issue，这块跟同步删除没关系，你开启了下载任务清理插件后，在历史记录删除源文件就会触发，不是同步删除插件的问题。
