### ISSUE TITLE
请问movie这类的红色标签在哪

### ISSUE THREAD

**Issue by Ice-Cream-MY** [thsrite/emby_sync_del_nt#2]
![image](https://user-images.githubusercontent.com/76402568/228526781-19502c9e-72df-41bf-a915-693aa2266c6d.png)

**Comment by thsrite** [comment]
where下第三个Text

**Comment by Ice-Cream-MY** [comment]
> where下第三个Text

![image](https://user-images.githubusercontent.com/76402568/228543918-c2515ef1-8939-42a4-ab2c-00cc365999bd.png)
不不好意思再次打扰，根据配置设置以后无法联动nt，日志里也没有信息，配置我检查了一遍没问题，地址也没错

**Comment by thsrite** [comment]
> > where下第三个Text
> 
> ![image](https://user-images.githubusercontent.com/76402568/228543918-c2515ef1-8939-42a4-ab2c-00cc365999bd.png) 不好意思再次打扰，根据配置设置以后无法联动nt，日志里也没有信息，配置我检查了一遍没问题，地址也没错

再看下[README.md](https://github.com/thsrite/emby_sync_del_nt#readme)  替换下版本即可

**Comment by Ice-Cream-MY** [comment]
> > > where下第三个Text
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/76402568/228543918-c2515ef1-8939-42a4-ab2c-00cc365999bd.png) 不好意思再次打扰，根据配置设置以后无法联动nt，日志里也没有信息，配置我检查了一遍没问题，地址也没错
> 
> 再看下[README.md](https://github.com/thsrite/emby_sync_del_nt#readme) 替换下版本即可

感谢作者大大解答，改了以后ok了

**Comment by Ice-Cream-MY** [comment]
> > > > where下第三个Text
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/76402568/228543918-c2515ef1-8939-42a4-ab2c-00cc365999bd.png) 不好意思再次打扰，根据配置设置以后无法联动nt，日志里也没有信息，配置我检查了一遍没问题，地址也没错
> > 
> > 
> > 再看下[README.md](https://github.com/thsrite/emby_sync_del_nt#readme) 替换下版本即可
> 
> 感谢作者大大解答，改了以后ok了

测试了电视剧 动漫都可以触发，电影没办法触发

**Comment by thsrite** [comment]
> > > > > where下第三个Text
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/76402568/228543918-c2515ef1-8939-42a4-ab2c-00cc365999bd.png) 不好意思再次打扰，根据配置设置以后无法联动nt，日志里也没有信息，配置我检查了一遍没问题，地址也没错
> > > 
> > > 
> > > 再看下[README.md](https://github.com/thsrite/emby_sync_del_nt#readme) 替换下版本即可
> > 
> > 
> > 感谢作者大大解答，改了以后ok了
> 
> 测试了电视剧 动漫都可以触发，电影没办法触发 所使用的是4.7 X3版本

再对比下文件，movie那个json看看里面参数是不是都加引号了

**Comment by Ice-Cream-MY** [comment]
> > > > > > where下第三个Text
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/76402568/228543918-c2515ef1-8939-42a4-ab2c-00cc365999bd.png) 不好意思再次打扰，根据配置设置以后无法联动nt，日志里也没有信息，配置我检查了一遍没问题，地址也没错
> > > > 
> > > > 
> > > > 再看下[README.md](https://github.com/thsrite/emby_sync_del_nt#readme) 替换下版本即可
> > > 
> > > 
> > > 感谢作者大大解答，改了以后ok了
> > 
> > 
> > 测试了电视剧 动漫都可以触发，电影没办法触发 所使用的是4.7 X3版本
> 
> 再对比下文件，movie那个json看看里面参数是不是都加引号了

加了的，我是用的你后面更新的版本

**Comment by thsrite** [comment]
> > > > > > > where下第三个Text
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/76402568/228543918-c2515ef1-8939-42a4-ab2c-00cc365999bd.png) 不好意思再次打扰，根据配置设置以后无法联动nt，日志里也没有信息，配置我检查了一遍没问题，地址也没错
> > > > > 
> > > > > 
> > > > > 再看下[README.md](https://github.com/thsrite/emby_sync_del_nt#readme) 替换下版本即可
> > > > 
> > > > 
> > > > 感谢作者大大解答，改了以后ok了
> > > 
> > > 
> > > 测试了电视剧 动漫都可以触发，电影没办法触发 所使用的是4.7 X3版本
> > 
> > 
> > 再对比下文件，movie那个json看看里面参数是不是都加引号了
> 
> 加了的，我是用的你后面更新的版本

那应该不会，我最先用4.7测试的就是电影  你再检查下
