### ISSUE TITLE
全部配置好后，nastool没有反应。

### ISSUE THREAD

**Issue by CookieJaySJ** [thsrite/emby_sync_del_nt#5]
这是我的配置图：
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/10297471/229222029-ce14720b-1bd3-450a-97f3-65e6712cd0a0.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/10297471/229222093-ef1fa0cd-7c21-429e-9506-602c5ad6b6cd.png">
Nastool只能接收到emby发来的测试webhook，删除电视剧集没有收到信息：
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/10297471/229222473-df3a463a-cad5-44aa-b55d-d819320c1129.png">

请问大佬，我哪里有问题吗？

**Comment by thsrite** [comment]
tg晚上给你远程

**Comment by CookieJaySJ** [comment]
> tg晚上给你远程

好的，tg上私聊你的也是我。   大佬晚上几点有空？
