### ISSUE TITLE
emby日志报错。。威联通docekr和原生包都试了，看不懂日志报错是什么意思

### ISSUE THREAD

**Issue by dmdy123** [thsrite/emby_sync_del_nt#6]
似乎不是路径的问题，我 尝试填写错误路径，日志会报路径错误
![1H`3$}VTHT(%PJZM5)UBR%O](https://user-images.githubusercontent.com/129559686/229245451-a27be56e-a7c4-4f0b-98b7-1ec525702bdf.png)

![C($(UIZZOKG4)`IEOB$BHZV](https://user-images.githubusercontent.com/129559686/229245476-b83a2284-bad1-46f3-9258-99dca5b0a79b.png)
尝试过4,7+3.0版本也是这个错误 期待大佬回复

**Comment by thsrite** [comment]
现在是什么版本，把你用的四个参数文件中随便一个截图看看

**Comment by dmdy123** [comment]
![_OZ5L%NUGW}HP{$EQXJA06G](https://user-images.githubusercontent.com/129559686/229289759-381a6f33-0b40-4f83-ab42-bc64da271bf6.png)
 感谢大佬回复   这个是文件截图  emby版本：4.8.0.27  插件文件包用的emby4.8-ScripterX4这个文件夹下的

**Comment by dmdy123** [comment]
> 现在是什么版本，把你用的四个参数文件中随手一个截图看

![_OZ5L%NUGW}HP{$EQXJA06G](https://user-images.githubusercontent.com/129559686/229289946-73494609-3243-4972-8d7f-84708b3460e1.png)

感谢大佬回复 这个是文件截图 emby版本：4.8.0.27 插件文件包使用的emby4.8-ScripterX4这个文件夹下的

**Comment by thsrite** [comment]
tg 找我 远程看看

**Comment by dmdy123** [comment]
> tg 找我 远程看看

最新进展，emby4.8版本+ScripterX-3.0版本 配合emby4.7-ScripterX3的文件包  已经可以正常发post  可以正常删除源文件
一直被文件夹名字emby4.8-ScripterX4 给限制了思路 以为emby4.8只能搭配ScripterX4.0版本
问题已经解决  但是我看也有很多人出现4.8的emby不发包问题  可能都是相同情况  大佬要不考虑改下教程 直接 4.7和4.8都让用ScripterX3   要么4版本插件有些不太适配  或者发包参数语法的问题

**Comment by dmdy123** [comment]
> 

问题并没有解决。。emby会自动更新插件到最新版 这个很烦  暂时也找不到emby插件禁止更新的方法

**Comment by CookieJaySJ** [comment]
> > tg 找我 远程看看
> 
> 最新进展，emby4.8版本+ScripterX-3.0版本 配合emby4.7-ScripterX3的文件包 已经可以正常发post 可以正常删除源文件 一直被文件夹名字emby4.8-ScripterX4 给限制了思路 以为emby4.8只能搭配ScripterX4.0版本 问题已经解决 但是我看也有很多人出现4.8的emby不发包问题 可能都是相同情况 大佬要不考虑改下教程 直接 4.7和4.8都让用ScripterX3 要么4版本插件有些不太适配 或者发包参数语法的问题

请问4.8.0.27配合ScripterX3可以正常使用么？   我昨天使用4.8.0.28版本的emby配合Scripterx4不成功，然后大佬给我降级到4.8.0.21就成功了

**Comment by CookieJaySJ** [comment]
> 问题并没有解决。。emby会自动更新插件到最新版 这个很烦 暂时也找不到emby插件禁止更新的方法

emby自动给你把Scripterx3升级到x4了？

**Comment by dmdy123** [comment]
> > 问题并没有解决。。emby会自动更新插件到最新版 这个很烦 暂时也找不到emby插件禁止更新的方法
> 
> emby自动给你把Scripterx3升级到x4了？

是的  自动升级了。。。 安装低版本  几分钟以后emby就会自动升级最新版本。  不知道怎么屏蔽

**Comment by dmdy123** [comment]
> 

那应该就是Scripter-x和新版emby的兼容问题了   要么先用支持Scripter-x4的 4.8.0.21emby版本  要么就再等等后续有没有新的解决办法了

**Comment by thsrite** [comment]
手动方式安装插件应该不会自动更新，不要通过插件市场了

**Comment by dmdy123** [comment]
> 手动方式安装插件应该不会自动更新，不要通过插件市场了

Scripter-x官方似乎已经找不到3版本  我在插件市场安装了3.0.5.5版本，在它更新前把dll文件拷贝了出来 希望给后边用得上的人使用

[EmbyScripterX.zip](https://github.com/thsrite/emby_sync_del_nt/files/11131263/EmbyScripterX.zip)

使用方法：emby后台-插件  找到新版本卸载掉  最好先重启下    然后把  EmbyScripterX.dll  文件拷贝到emby的/config/plugins/文件夹下 再重启下emby 就安装成功了

**Comment by dmdy123** [comment]
> > 
> 
> 那应该就是Scripter-x和新版emby的兼容问题了 要么先用支持Scripter-x4的 4.8.0.21emby版本 要么就再等等后续有没有新的解决办法了

看最新回复，新的方法

**Comment by dmdy123** [comment]
> 

手动安装也会更新。刚试了

**Comment by dmdy123** [comment]
> 貌似，emby4.8.0.21以上版本用scripterx4版本有点问题。 手动方式安装插件应该不会自动更新，不要通过插件市场了

手动安装也会更新。刚试了

**Comment by thsrite** [comment]
emby换4.8.0.21

> > 貌似，emby4.8.0.21以上版本用scripterx4版本有点问题。 手动方式安装插件应该不会自动更新，不要通过插件市场了
> 
> 手动安装也会更新。刚试了

**Comment by dmdy123** [comment]
> emby换4.8.0.21
> 
> > > 貌似，emby4.8.0.21以上版本用scripterx4版本有点问题。 手动方式安装插件应该不会自动更新，不要通过插件市场了
> > 
> > 
> > 手动安装也会更新。刚试了

最终极解决方案：我把3.0.5.5的EmbyScripterX.dll文件做了反编译 改了下版本号，现在版本号显示4.0.0.8了
emby检测到是最新版本就不会更新了  （已经测试过可以正常运行，几个小时了也没有再被自动升级）
文件放上来给有需要的朋友
[EmbyScripterX.zip](https://github.com/thsrite/emby_sync_del_nt/files/11131706/EmbyScripterX.zip)
使用方法： 适用于emby4.8以上版本，先卸载之前安装的4.0.0.8版本，重启emby 然后上传EmbyScripterX.dll文件到emb  /config/plugins/文件夹 重启后就可以配置使用了  
注意：版本只是显示4.0.0.8  实际还是3.0版本 需要使用ScripterX3的nastool_plugin参数文件

另外怎么联系大佬tg  在tg wiki和频道都没有找到个人tg
