### ISSUE TITLE
电影无法删除

### ISSUE THREAD

**Issue by Ice-Cream-MY** [thsrite/emby_sync_del_nt#7]
![image](https://user-images.githubusercontent.com/76402568/229369500-c43c2f5f-1531-403b-993b-a958b22f29ea.png)
![image](https://user-images.githubusercontent.com/76402568/229369515-dfad58a5-929e-4664-8b82-198ddb7fa9b0.png)
![image](https://user-images.githubusercontent.com/76402568/229369581-8e036b9d-46a6-4f75-b4a1-7313597ed8de.png)
![image](https://user-images.githubusercontent.com/76402568/229369596-608155c1-e39d-4a67-b23e-9d7ac5194a10.png)

经过反复对比还是无法找出问题所在，配置也检查了没问题，希望作者大大指导一下，我删除了一部电影进行测试，nt日志报错

**Comment by thsrite** [comment]
Scripter X什么版本

**Comment by Ice-Cream-MY** [comment]
> Scripter X什么版本

3.0.5

**Comment by thsrite** [comment]
https://github.com/thsrite/emby_sync_del_nt/issues/6#issuecomment-1493281729
手动安装这个插件版本试试

**Comment by Ice-Cream-MY** [comment]
> [#6 (comment)](https://github.com/thsrite/emby_sync_del_nt/issues/6#issuecomment-1493281729) 手动安装这个插件版本试试

![image](https://user-images.githubusercontent.com/76402568/229514624-e5dbd2d8-9748-4e8f-8d0a-835e8a5c9a93.png)
![image](https://user-images.githubusercontent.com/76402568/229514626-3d8ba4a5-8aef-435b-883e-5ef3f01ac861.png)

**Comment by thsrite** [comment]
tg nt群找我，远程看看

**Comment by Ice-Cream-MY** [comment]
作者指点已经好了，自己的问题，感谢作者大大
