### ISSUE TITLE
自己删除剧集

### ISSUE THREAD

**Issue by 42012606** [thsrite/emby_sync_del_nt#9]
半夜自己帮我删了一部纪录片，我找不到日志，顶没了
![image](https://user-images.githubusercontent.com/104238407/230696106-18f43e46-aeb2-4acd-b565-fe23e1ddbaf4.png)

**Comment by 42012606** [comment]
emby版本 4.8.0.0.21
ScripterX版本 4.0.0.8

**Comment by thsrite** [comment]
等下个版本修复吧，删除的时候是不是正好有新的剧集入库

**Comment by thsrite** [comment]
等下个版本修复吧，删除的时候是不是正好有新的剧集入库

**Comment by 42012606** [comment]
> 等下个版本修复吧，删除的时候是不是正好有新的剧集入库

好的，感谢回复。是有入库，rss任务下载时间凌晨1点10分左右。间隔20分钟左右触发了删除。

**Comment by thsrite** [comment]
更新nastool，然后根据教程新增参数就行
